kind: Service
apiVersion: v1
metadata:
  name: nextjs-hello-world-app-service
spec:
  type: NodePort
  selector:
    app: nextjs-hello-world-app
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-hello-world-app-deployment
  labels:
    app: nextjs-hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-hello-world-app
  template:
    metadata:
      labels:
        app: nextjs-hello-world-app
    spec:
      containers:
      - name: nextjs-hello-world-app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
