apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-hello-world-app-deployment
  labels:
    app: nextjs-hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-hello-world-app
  template:
    metadata:
      labels:
        app: nextjs-hello-world-app
    spec:
      containers:
      - name: nextjs-hello-world-app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
